[pytest]
DJANGO_SETTINGS_MODULE = InvenTree.settings
python_files = bench_*.py test_*.py
python_classes = Bench* Test*
python_functions = bench_* test_*
addopts = --reuse-db
testpaths = src/backend/InvenTree
