name: CodSpeed

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  python_version: 3.11
  INVENTREE_DB_ENGINE: sqlite3
  INVENTREE_DB_NAME: inventree_bench
  INVENTREE_DEBUG: false

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # pin@v6.0.1
        with:
          persist-credentials: false

      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # pin@v6.1.0
        with:
          python-version: ${{ env.python_version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r src/backend/requirements.txt
          pip install pytest-codspeed

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: pytest benchmarks/ --codspeed
